# Generated by Django 4.1.7 on 2023-03-13 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_topic_rename_created_room_created_room_host_message_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
